name: run_fromcomment

on:
  issue_comment:                                     
    types: created

jobs:
 job01:
   if: contains(github.event.comment.body, 'runtestbed')   # check the comment if it contains the keywords
   runs-on: [ubuntu-latest]
   steps:
     - name: say hello
       run: |
         github.event.inputs.USER=`echo "${{ github.event.comment.body }}"  | cut -d' ' -f2 | cut -d':' -f1`
         github.event.inputs.HID=`echo "${{ github.event.comment.body }}"  | cut -d' ' -f2 | cut -d':' -f2`       
     - name: Create config file # seems necessary
       run: |          mkdir $HOME/.ssh 
         echo "Host=ec" > $HOME/.ssh/config
         echo "HostName=ecaccess.ecmwf.int" >> $HOME/.ssh/config
         echo "user=${{ github.event.inputs.USER }}" >> $HOME/.ssh/config
         echo "KexAlgorithms=+diffie-hellman-group1-sha1" >> $HOME/.ssh/config
         echo "HostkeyAlgorithms=+ssh-dss" >> $HOME/.ssh/config
         echo "Ciphers=+aes128-cbc" >> $HOME/.ssh/config
         echo "StrictHostKeyChecking=no" >> $HOME/.ssh/config
         cat $HOME/.ssh/config
     - name: Install expect
       run: sudo apt install expect
     - name: Create expect file
       run: | 
          echo "#!/usr/bin/expect -f" > expect.sh
          echo "spawn ssh ec" >> expect.sh
          echo "expect \"*password: \"" >> expect.sh
          echo "send \"${{ github.event.inputs.HID }}\r\"" >> expect.sh
          echo "expect \"*: \" {send \"\r\"}" >> expect.sh
          echo "expect \"*\$ \" {send \"touch blabla2\r\"}" >> expect.sh
          echo "expect \"*\$ \" {send \"exit\r\"}" >> expect.sh
          chmod 755 expect.sh 
          cat expect.sh
    - name: executing remote ssh commands using password
      run: ./expect.sh
