name: run_fromcomment

on:
  issue_comment:                                     
    types: [created]

jobs:
  job01:
  
  
    if: contains(github.event.comment.body, 'runtestbed_self')   # check the comment if it contains the keywords
    runs-on: [self-hosted]    
    steps:
      - name: Clone git repo
        uses: actions/checkout@v2
      - name: Checkout Pull Request
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUM=${PR_URL##*/}
          echo "Checking out from PR #$PR_NUM based on URL: $PR_URL"
          hub pr checkout $PR_NUM
      
